#!/bin/sh
# $Id: ps2pdf 11016 2010-04-05 17:22:10Z hintak $
# Convert PostScript to PDF.

# Currently, we produce PDF 1.4 by default, but this is not guaranteed
# not to change in the future.
version=14

ps2pdf="`dirname \"$0\"`/ps2pdf$version"
if test ! -x "$ps2pdf"; then
	ps2pdf="ps2pdf$version"
fi
exec "$ps2pdf" "$@"
