#!/bin/sh
# $Id: ps2pdf14 11016 2010-04-05 17:22:10Z hintak $
# Convert PostScript to PDF 1.4 (Acrobat 5-and-later compatible).
ps2pdfwr="`dirname \"$0\"`/ps2pdfwr"
if test ! -x "$ps2pdfwr"; then
	ps2pdfwr="ps2pdfwr"
fi
exec "$ps2pdfwr" -dCompatibilityLevel=1.4 "$@"
